language: android
jdk: oraclejdk8
dist: trusty
before_cache:
  - "rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock"
  - "rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
before_install:
  - echo "artifactory_username=$ARTIFACTORY_USERNAME" > gradle.properties
  - echo "artifactory_password=$ARTIFACTORY_PASSWORD" >> gradle.properties
  - echo "artifactory_path_android_libraries=https://blockone.jfrog.io/blockone/android-libs" >> gradle.properties
  - echo "artifactory_contextURL=https://blockone.jfrog.io/blockone" >> gradle.properties
  - echo "artifactory_repo=default" >> gradle.properties

before_deploy:
  - echo "artifactory_username=$ARTIFACTORY_USERNAME" > gradle.properties
  - echo "artifactory_password=$ARTIFACTORY_PASSWORD" >> gradle.properties
  - echo "artifactory_path_android_libraries=https://blockone.jfrog.io/blockone/android-libs" >> gradle.properties
  - echo "artifactory_contextURL=https://blockone.jfrog.io/blockone" >> gradle.properties
  - echo "artifactory_repo=default" >> gradle.properties


deploy:
  - skip_cleanup: true
  # feature branches deploy to feature-local
  - provider: script
    skip_cleanup: true
    script: "bash scripts/deploy-artifactory.sh 'android-libs-feature-local'"
    on:
      all_branches: true
      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^feature\/.*$
  # develop deploys to dev local
  - provider: script
    skip_cleanup: true
    script: "bash scripts/deploy-artifactory.sh 'android-libs-dev-local'"
    on:
      branch:
        - develop
  # release branches and master deploy to release local
  - provider: script
    skip_cleanup: true
    script: "bash scripts/deploy-artifactory.sh 'android-libs-release-local'"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH == master || ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^release\/.*$
  # tagged releases from master, go to distribution
  - provider: script
    skip_cleanup: true
    script: "bash scripts/deploy-artifactory.sh 'eosiojava-product-eosio-dist'"
    on:
      tags: true
      branch: master

after_deploy:
  - echo "cleaning up properties"
  - rm gradle.properties

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
